---
title: "Lesson 2 - Exercises"
author: "Corn? Oosthuizen - OSTAND005"
date: "21 August 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=TRUE, eval = TRUE}
suppressMessages(library(tidyverse))

load("output/recommender.RData")

sorted_my_users <- as.character(unlist(viewed_movies[,1]))
viewed_movies <- as.matrix(viewed_movies[,-1])
row.names(viewed_movies) <- sorted_my_users

```

## Exercises

1. Adapt the pairwise similarity function so that it doesn't use loops.

```{r}

# Exercises:
# 1. Adapt the pairwise similarity function so that it doesn't use loops.

# cosine_sim <- function(a,b){ crossprod(a,b) / sqrt(crossprod(a)*crossprod(b)) }

cosineDist <- function(x) {
  as.matrix( tcrossprod(x) / sqrt(rowSums(x^2) %*% t(rowSums(x^2))) ) 
}

b <- cosineDist(viewed_movies)
row.names(b) <- row.names(viewed_movies) # user by user
colnames(b) <- row.names(viewed_movies)
#b
```

2. Implement a k-nearest-neighbours version of item-based collaborative filtering.

```{r}

#
#knn_ids <- c(names(sort(user_similarities["149",], decreasing = T))[1:5]) # does not include 149
# "303" "200" "177" "408" "426"

knn_ids <- c(names(sort(b["149",], decreasing = T))[2:6]) # gives us 149 as the first one
# "303" "200" "177" "408" "426"

viewed_movies[knn_ids,]
```

3. Adapt the `recommender_accuracy()` function so that it can be used with an arbitrary number of users and movies.


4. Experiment with the optimizers used in the matrix factorization collaborative filter.



